# Generated by Django 5.2.7 on 2025-11-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='field_heroes/', verbose_name='Фоновое изображение Hero'),
        ),
    ]
